# Generated by Django 5.2.14 on 2026-05-14 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric')], db_index=True, max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20)),
                ('seating_capacity', models.PositiveSmallIntegerField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('is_driver_available', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('under_service', 'Under Service'), ('not_available', 'Not Available')], db_index=True, default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('half_day_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('full_day_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_day_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='cars.car')),
            ],
        ),
    ]
